name: unit-test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: './go.mod'

      # Step 3: Install Go dependencies (modules)
      - name: Install dependencies
        run: go mod tidy  # This ensures Go dependencies are up-to-date

      # Step 4: Run Go tests
      - name: Run unit tests
        run: go test -v ./...
